#spring:
#  security:
#    user:
#      name: buzz
#      password: infinity

pancake:
  orders:
    pageSize: 10


  discount:
    codes:
      abcdef: 10
    
---
spring:
  profiles: prod
  
  datasource:
    url: jdbc:mysql://localhost/pancakecloud
    username: panuser
    password: panpass
    
logging:
  level:
    pancakes: WARN
    
